---
name: freegemas    # you probably want to 'snapcraft register <name>'
base: core20
version: '0.1'
summary: Open Source version of the well known Bejeweled game
license: GPL-2.0
description: |
  Bejeweled is a tile-matching puzzle video game by PopCap Games,
  developed for browsers in 2001. The goal is to clear gems of the
  same color, potentially causing a chain reaction. The game sold
  over 10 million copies and has been downloadedmore than 150 million times
icon: freegemas.png
grade: devel
confinement: classic

parts:
  freegemas:
    source: .
    plugin: cmake
    configflags: [ -DCMAKE_INSTALL_PREFIX=/usr ]
    build-packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev

apps:
  freegemas:
    command: usr/bin/freegemas
    desktop: usr/share/applications/freegemas.desktop
