---
name: freegemas    # you probably want to 'snapcraft register <name>'
base: core18
version: '0.1'
summary: Open Source version of the well known Bejeweled game
license: GPL-2.0
description: |
  Bejeweled is a tile-matching puzzle video game by PopCap Games,
  developed for browsers in 2001. The goal is to clear gems of the
  same color, potentially causing a chain reaction. The game sold
  over 10 million copies and has been downloadedmore than 150 million times
icon: freegemas.png
grade: devel
confinement: classic

parts:
  freegemas:
    source: .
    plugin: cmake
    configflags: [ -DCMAKE_INSTALL_PREFIX=/usr ]
    build-packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
    stage-packages:
      - libacl1
      - libacl1-kerberos4kth
      - libalgorithm-merge-perl
      - libalien-wxwidgets-perl
      - libansicolor-perl
      - libanyevent-perl
      - libapache2-mod-passenger
      - libapparmor1
      - libapt-inst1.5
      - libapt-pkg
      - libapt-pkg5.0
      - libaqsis1
      - libarchive-tar-perl
      - libarchive13
      - libargon2-0
      - libasan4
      - libasan4-dbg
      - libasn1-8-heimdal
      - libasound2
      - libasound2-data
      - libasound2-doc
      - libasound2-plugin-equal
      - libasound2-plugins
      - libassimp3
      - libassuan0
      - libasyncns0
      - libatomic1
      - libatomic1-dbg
      - libattr1
      - libattribute-handlers-perl
      - libaudit-common
      - libaudit0
      - libaudit1
      - libautodie-perl
      - libbinutils
      - libblkid1
      - libboost-date-time1.55.0
      - libboost-filesystem1.65.1
      - libboost-system1.65.1
      - libbsd0
      - libbz2
      - libbz2-1.0
      - libc-bin
      - libc-dev-bin
      - libc0.1
      - libc0.3
      - libc6
      - libc6-amd64
      - libc6.1
      - libcap-ng0
      - libcap2
      - libcapnp-0.6.1
      - libcc1-0
      - libcilkrts5
      - libcilkrts5-dbg
      - libcom-err2
      - libcomerr2
      - libcommon-sense-perl
      - libcompress-raw-bzip2-perl
      - libcompress-raw-zlib-perl
      - libcompress-zlib-perl
      - libcpan-meta-perl
      - libcpan-meta-requirements-perl
      - libcpan-meta-yaml-perl
      - libcpprest2.2
      - libcryptsetup12
      - libcurl3
      - libcurl4
      - libdap17
      - libdapclient6
      - libdapserver7
      - libdavix0
      - libdb5.3
      - libdballe6
      - libdbus-1-3
      - libdebconfclient0
      - libdevmapper1.02
      - libdevmapper1.02.1
      - libdiet-admin2.8
      - libdiet-client2.8
      - libdiet-sed2.8
      - libdigest-md5-perl
      - libdigest-perl
      - libdigest-sha-perl
      - libdpkg-perl
      - libdrm-amdgpu1
      - libdrm-common
      - libdrm-intel1
      - libdrm-nouveau2
      - libdrm-radeon1
      - libdrm2
      - libedit2
      - libegl-mesa0
      - libegl-vendor
      - libegl1
      - libegl1-mesa
      - libelf1
      - libencode-perl
      - libexception-class-perl
      - libexpat1
      - libexperimental-perl
      - libext2fs2
      - libextutils-cbuilder-perl
      - libextutils-command-perl
      - libextutils-install-perl
      - libextutils-parsexs-perl
      - libfakeroot
      - libfdisk1
      - libffi6
      - libfile-fcntllock-perl
      - libfile-path-perl
      - libfile-spec-perl
      - libfile-temp-perl
      - libflac8
      - libfluidsynth1
      - libfreefem++
      - libfreetype6
      - libfuse2
      - libgazebo5
      - libgbm1
      - libgcc1
      - libgcc1-dbg
      - libgcrypt20
      - libgdbm-compat4
      - libgdbm5
      - libgetfem4++
      - libgirepository-1.0-1
      - libgl1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglapi-mesa
      - libgldispatch0-nvidia
      - libgles1
      - libgles1-mesa
      - libgles2
      - libgles2-mesa
      - libglib2.0-0
      - libglib2.0-0-dbg
      - libglib2.0-bin
      - libglib2.0-data
      - libglib2.0-dev-bin
      - libglib2.0-doc
      - libglu1
      - libglu1-mesa
      - libglvnd0
      - libglx-mesa0
      - libglx-vendor
      - libglx0
      - libgmp10
      - libgmp3
      - libgmsh2
      - libgnutls30
      - libgomp1
      - libgomp1-dbg
      - libgpg-error0
      - libgpm2
      - libgssapi-krb5-2
      - libgssapi3
      - libgssapi3-heimdal
      - libgtk2-perl-doc
      - libgtk3-perl
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhogweed4
      - libhtml-template-compiled-perl
      - libhttp-tiny-perl
      - libhx509-5-heimdal
      - libi18n-langtags-perl
      - libibus-1.0-5
      - libice-doc
      - libice6
      - libicu60
      - libidn11
      - libidn2-0
      - libinsighttoolkit4.6
      - libio-compress-base-perl
      - libio-compress-bzip2-perl
      - libio-compress-perl
      - libio-compress-zlib-perl
      - libio-socket-ip-perl
      - libio-zlib-perl
      - libip4tc0
      - libisl-dbg
      - libisl19
      - libitm1
      - libitm1-dbg
      - libjack-0.116
      - libjack-0.125
      - libjack-jackd2-0
      - libjack0
      - libjbig0
      - libjcode-perl
      - libjna-java
      - libjpeg-turbo8
      - libjpeg8
      - libjson-c3
      - libjson-pp-perl
      - libjsoncpp1
      - libk5crypto3
      - libkadm5clnt-mit9
      - libkadm5srv-mit9
      - libkdb5-8
      - libkeyutils1
      - libkgeomap2
      - libkmod2
      - libkolabxml1
      - libkrb5-26-heimdal
      - libkrb5-3
      - libkrb5support0
      - libksba8
      - libkvkontakte1
      - libldap-2.3-0
      - libldap-2.4-2
      - libldap-common
      - libldap2
      - libllvm10
      - libload-perl
      - liblocale-codes-perl
      - liblocale-gettext-perl
      - liblocale-maketext-perl
      - liblocale-maketext-simple-perl
      - liblockfile-bin
      - liblockfile1
      - liblsan0
      - liblsan0-dbg
      - liblvm2app2.2
      - liblz4-1
      - liblzma5
      - liblzo2-2
      - libmad0
      - libmarc-charset-perl
      - libmarisa0
      - libmath-bigint-perl
      - libmath-complex-perl
      - libmediawiki1
      - libmime-base64-perl
      - libmirclient9
      - libmircommon7
      - libmircookie2
      - libmircore1
      - libmirprotobuf3
      - libmodplug1
      - libmodule-corelist-perl
      - libmodule-load-conditional-perl
      - libmodule-load-perl
      - libmodule-metadata-perl
      - libmount1
      - libmpc3
      - libmpdec2
      - libmpdec2.3
      - libmpfr6
      - libmpx0
      - libmpx2
      - libmpx2-dbg
      - libncurses5
      - libncursesw5
      - libnet-jifty-perl
      - libnet-ldap-perl
      - libnet-perl
      - libnet-ping-perl
      - libnettle6
      - libnghttp2-14
      - libnpth0
      - libnss-systemd
      - libogg0
      - libogre-1.8.0
      - libogre-1.9.0
      - libopengl-perl
      - libopengl0
      - libopenwalnut1
      - libp11-kit0
      - libpam-doc
      - libpam-mkhomedir
      - libpam-modules
      - libpam-modules-bin
      - libpam-motd
      - libpam-runtime
      - libpam-ssh
      - libpam-systemd
      - libpam-umask
      - libpam0g
      - libpam0g-util
      - libparams-check-perl
      - libparent-perl
      - libparse-cpan-meta-perl
      - libpciaccess0
      - libpcre-ocaml
      - libpcre16-3
      - libpcre3
      - libpcre32-3
      - libpcrecpp0
      - libpcrecpp0v5
      - libperl-apireference-perl
      - libperl-ostype-perl
      - libperl5.26
      - libpng16-16
      - libpod-escapes-perl
      - libpod-parser-perl
      - libpod-simple-perl
      - libpqxx-4.0
      - libprocps6
      - libprotobuf-lite10
      - libprotobuf10
      - libpsl5
      - libpulse-mainloop-glib0
      - libpulse0
      - libpython3-stdlib
      - libpython3.4-minimal
      - libpython3.5-minimal
      - libpython3.6-minimal
      - libpython3.6-stdlib
      - libpython3.6-testsuite
      - libpython3.7-stdlib
      - libqtcore4-perl
      - libqtgui4-perl
      - libquadmath0
      - libquadmath0-dbg
      - libreadline-common
      - libreadline4
      - libreadline5
      - libreadline7
      - libregexp-optimizer-perl
      - libreoffice-core
      - librhash0
      - librime1
      - libroken18-heimdal
      - librtmp1
      - libsamplerate0
      - libsasl2
      - libsasl2-2
      - libsasl2-modules
      - libsasl2-modules-db
      - libsbuild-perl
      - libscalar-list-utils-perl
      - libsdl-1.3-0
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libseccomp2
      - libselinux1
      - libsemanage-common
      - libsemanage1
      - libsensors4
      - libsepol1
      - libsm-doc
      - libsm6
      - libsmartcols1
      - libsmbclient
      - libsndfile1
      - libsndio6.1
      - libsoap-lite-perl
      - libsocket-perl
      - libsqlite3-0
      - libss2
      - libssl1.0.0
      - libssl1.0.2
      - libssl1.1
      - libstdc++-7-doc
      - libstdc++6
      - libstdc++6-7-dbg
      - libstdc++6-8-dbg
      - libstorable-perl
      - libsys-syslog-perl
      - libsystemd0
      - libtasn1-6
      - libterm-readline-gnu-perl
      - libterm-readline-perl-perl
      - libtest-harness-perl
      - libtest-simple-perl
      - libtest-tester-perl
      - libtest-use-ok-perl
      - libthread-queue-perl
      - libthreads-perl
      - libthreads-shared-perl
      - libtiff5
      - libtime-hires-perl
      - libtime-local-perl
      - libtime-piece-perl
      - libtinfo5
      - libtirpc1
      - libtool
      - libtsan0
      - libtsan0-dbg
      - libubsan0
      - libubsan0-dbg
      - libudev1
      - libunicode-collate-perl
      - libunistring2
      - libuuid1
      - libuv1
      - libversion-perl
      - libversion-requirements-perl
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwayland-bin
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-doc
      - libwayland-egl1
      - libwayland-egl1-mesa
      - libwayland-server0
      - libwayland0
      - libwebp6
      - libwind0-heimdal
      - libwrap0
      - libwreport2
      - libx11-6
      - libx11-data
      - libx11-doc
      - libx11-xcb1
      - libxau6
      - libxcb-doc
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxcb-randr0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext-doc
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml-parser-lite-tree-perl
      - libxml2
      - libxmltooling6
      - libxrandr2
      - libxrender1
      - libxshmfence1
      - libxsloader-perl
      - libxss1
      - libxt-doc
      - libxt6
      - libxv1
      - libxxf86vm1
      - libyaml-perl
      - libz1
      - libzstd1
      - zlib1g

apps:
  freegemas:
    command: usr/bin/freegemas
    desktop: usr/share/applications/freegemas.desktop
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - opengl
      - unity7
      - wayland
      - x11
